version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    ignored_updates:
      - match:
          dependency_name: "react-native"
      - match:
          dependency_name: "react-native-navigation"
      - match:
          dependency_name: "@types/react-native"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
